MAX_REVISION_CYCLES = 2
DEFAULT_TOP_K = 5
DEFAULT_GRAPH_MAX_HOPS = 2

# --- Vector store ---
DENSE_VECTOR_NAME = "dense"
SPARSE_VECTOR_NAME = "sparse"
EMBEDDING_DIMENSIONS = 1536  # text-embedding-3-small
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 250
